name: CI
on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request: { branches: [master] }
  schedule: [ cron: '4 11 28 * *' ]
  workflow_dispatch:


jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      VERBOSE: 1
    steps:
      - uses: actions/checkout@v4
      - run: shellcheck -S warning *.sh
      - run: sudo apt-get remove man-db
      - run: sudo apt-get install --no-install-recommends gzip git git-lfs openssl gpg
      - run: sudo apt-get install --no-install-recommends bash zsh ksh csh
      - run: time ./smoke-test.sh
      - run: time USE_GPG=1 ./smoke-test.sh
      - run: bash -c 'time ./smoke-test.sh'
      - run: zsh -c 'time ./smoke-test.sh'
      - run: ksh -c 'time ./smoke-test.sh'
      - run: csh -c 'time ./smoke-test.sh'


  test-macos:
    timeout-minutes: 5
    needs: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew install coreutils
      - run: ./smoke-test.sh


  deploy-docs:
    runs-on: ubuntu-latest
    needs: [test, test-macos]
    permissions:
      pages: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get remove man-db
      - run: sudo apt-get install aspell
      - run: .github/scripts/spellcheck.sh README.md
      - run: .github/scripts/spellcheck.sh README.full.md
      - run: pip install --user markdown
      - run: .github/scripts/build-website.sh
      - uses: peaceiris/actions-gh-pages@v4
        if: github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output


  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@f72ff1a1336129f29bf0166c0fd0ca6cf1bcb38c  # v1.2.1
