name: CI
on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request: { branches: [master] }
  schedule: [ cron: '4 11 28 * *' ]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      VERBOSE: 1
    steps:
      - uses: actions/checkout@v4
      - run: shellcheck -S warning *.sh
      - run: sudo apt-get install --no-install-recommends gzip git git-lfs openssl gpg
      - run: sudo apt-get install --no-install-recommends bash zsh ksh csh
      - run: time ./smoke-test.sh
      - run: time USE_GPG=1 ./smoke-test.sh
      - run: bash -c 'time ./smoke-test.sh'
      - run: zsh -c 'time ./smoke-test.sh'
      - run: ksh -c 'time ./smoke-test.sh'  # XXX: Why this fails?
        continue-on-error: true
      - run: csh -c 'time ./smoke-test.sh'
        continue-on-error: true  # XXX: Error: set: Variable name must begin with a letter.

  test-macos:
    timeout-minutes: 5
    needs: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./smoke-test.sh
