name: Deploy to gh-pages
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  pages: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install aspell
      - run: comm <(<README.full.md aspell list | sort -u) <(cat .github/aspell-ignorewords.txt) -23 | grep -q . || exit 1
      - run: pip install --user markdown
      - run: .github/scripts/build-website.sh
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
